version: "3.7"

services:

  gophish:
    image: "gophish/gophish"
    container_name: "gophish"
    volumes:
      - ${PWD}/gophishVolumes/config.json:/opt/gophish/config.json
      - ${PWD}/gophishVolumes/gophish.db:/opt/gophish/gophish.db
    labels:
      - "traefik.enable=true"
      # Web interface - host:3333 to gophish:3333
      - "traefik.tcp.routers.gophishUi.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gophishUi.service=gophishUi@docker"
      - "traefik.tcp.routers.gophishUi.entrypoints=gophish-ep"
      - "traefik.tcp.services.gophishUi.loadbalancer.server.port=3333"
networks:
  default:
    external:
      name: edgy-c2_default
